permalink: pretty
highlighter: rouge
url: https://playbooks.brighthive.io
google_analytics: UA-153784380-1

collections:
  - contact_tracing_plays
  - jobseeker_tools_plays

markdown: kramdown

sass:
    sass_dir: assets/_sass
